# Generated by Django 6.0.5 on 2026-05-21 15:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="用户ID/OpenID"
                    ),
                ),
                (
                    "password",
                    models.CharField(max_length=128, verbose_name="密码哈希值"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "用户信息",
                "verbose_name_plural": "用户信息",
                "db_table": "UserProfile",
            },
        ),
        migrations.CreateModel(
            name="ReportRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_no",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="报告编号"
                    ),
                ),
                (
                    "patient_image",
                    models.ImageField(
                        upload_to="cxr_images/", verbose_name="病人胸片图像"
                    ),
                ),
                (
                    "prediction_result",
                    models.TextField(verbose_name="疾病预测结果(字符串)"),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="报告生成时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="hello.userprofile",
                        to_field="user_id",
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "报告记录",
                "verbose_name_plural": "报告记录",
                "db_table": "report_record",
                "ordering": ["-generated_at"],
            },
        ),
    ]
