# Generated by Django 6.0.5 on 2026-05-21 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="userprofile",
            table="user_profile",
        ),
    ]
