# Generated by Django 5.2.14 on 2026-05-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_alter_userprofile_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_id',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='用户ID/OpenID'),
        ),
    ]
