# Generated by Django 5.2.14 on 2026-05-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_userprofile_avatar_url_userprofile_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='头像链接/路径'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, default='微信用户', max_length=64, null=True, verbose_name='用户昵称'),
        ),
    ]
