# Generated by Django 5.2.14 on 2026-06-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_remove_userprofile_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrecord',
            name='annotated_image',
            field=models.ImageField(blank=True, null=True, upload_to='annotatedes/'),
        ),
        migrations.AddField(
            model_name='reportrecord',
            name='heatmap_image',
            field=models.ImageField(blank=True, null=True, upload_to='heatmaps/'),
        ),
    ]
