# Generated by Django 5.2.14 on 2026-06-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_reportrecord_bbox_image_reportrecord_heatmap_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrecord',
            name='annotated_image',
            field=models.ImageField(blank=True, null=True, upload_to='annotateds/'),
        ),
    ]
