# Generated by Django 5.2.14 on 2026-06-09 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_alter_reportrecord_annotated_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportRecord',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
