# Generated by Django 5.2.14 on 2026-06-09 22:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_no', models.CharField(max_length=32, unique=True, verbose_name='报告编号')),
                ('patient_image', models.ImageField(upload_to='cxr_images/', verbose_name='病人胸片图像')),
                ('heatmap_image', models.ImageField(blank=True, null=True, upload_to='heatmaps/', verbose_name='热力图')),
                ('annotated_image', models.ImageField(blank=True, null=True, upload_to='annotateds/', verbose_name='标注图像')),
                ('prediction_result', models.TextField(verbose_name='疾病预测结果')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='报告生成时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='user.userprofile', to_field='user_id', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '报告记录',
                'verbose_name_plural': '报告记录',
                'db_table': 'report_record',
                'ordering': ['-generated_at'],
            },
        ),
    ]
