# Generated by Django 5.2.14 on 2026-06-09 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
        ('user', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='user.userprofile', verbose_name='所属用户'),
        ),
    ]
