"""
Django settings for demo project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 设置 Hugging Face 本地缓存路径
import os


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-+t76-u@cjfq6m7h8_^7a7ghc620o@#sht+@y(hh-n$40#i(y%="

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # 原有应用
    "hello.apps.HelloConfig",
    # 新模块化应用
    "apps.core",
    "apps.ai",
    "apps.ai.services",
    "apps.medical",
    "apps.user",
    "apps.report",
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "demo.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "demo.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        # 1. 声明使用的是 Django 自带的 mysql 引擎驱动
        "ENGINE": "django.db.backends.mysql",
        
        # 2. 你的数据库名字（需要先在 MySQL Workbench 中用 CREATE DATABASE 语句建好）
        "NAME": "new_schema", 
        
        # 3. 数据库管理员用户名，默认是 root
        "USER": "root",
        
        # 4. 你在安装 MySQL 8.0 时为 root 用户设置的密码
        "PASSWORD": "Dong2004921.",
        
        "HOST": "127.0.0.1",
        
        # 6. MySQL 8.0 的默认端口。如果你改动了，请填入修改后的端口
        "PORT": "3306",
        
        # 7. 可选配置：设置字符集，确保完全兼容微信小程序可能传过来的特殊字符或中文
        "OPTIONS": {
            "charset": "utf8mb4",
            # 解决旧版 mysqlclient 在某些特殊环境下的严格模式警告（可选）
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES',NAMES utf8mb4;",
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images) 
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# 1. 浏览器或小程序访问上传图片的 URL 前缀
MEDIA_URL = "/media/"

# 2. 图片在服务器硬盘上的物理保存绝对路径
MEDIA_ROOT =  BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ==================== Celery & Redis 配置 ====================
# Redis 作为 Broker (消息中间件) 和 Backend (结果存储)
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/1'

# 序列化配置
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# 关键：由于 PyTorch 在多进程下可能会有 CUDA 初始化冲突，
# 建议限制 worker 的并发数（如果是 GPU 推理，通常设为 1，或者用单独的单线程 worker 执行）
CELERY_WORKER_CONCURRENCY = 1



